# for the production only
version: '3.4'
services:
  db:
    container_name: mariadb
    image: mariadb:10.7
    restart: always
    environment:
      - MYSQL_USER=milon27
      - MYSQL_PASSWORD=myPassWord
      - MYSQL_ROOT_PASSWORD=myPassWord
      - MYSQL_DATABASE=test_db
    ports:
      - 3002:3306
    volumes:
      - mysql_vol:/var/lib/mysql

#volumes(root label)
volumes:
  mysql_vol: {}