version: '3.4'
services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: always
    depends_on:
      - db
      - client_build
    ports:
      - 3000:80 #client
      - 2727:2727 #api
    volumes:
      - ./_nginx/config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./_nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/dist:/usr/share/nginx/html

  client_build:
    build:
      context: ./client
    image: milon27/vite-react
    volumes:
      - ./client/dist:/app/dist
    environment:
      - VITE_APP_API=http://164.92.156.138:2727
      - VITE_APP_NAME=CICD-GACTION

  server:
    container_name: server
    build:
      context: ./server
      target: production
    image: milon27/node-mysql
    restart: always
    depends_on:
      - db
    environment:
      - PORT=2727
      - DB_HOST=db
      - DB_USER=milon27
      - DB_PASS=myPassWord
      - DB_NAME=my_db
      - NODE_ENV=production_cicd

  db:
    container_name: mariadb
    image: mariadb:10.7
    restart: always
    environment:
      - MYSQL_USER=milon27
      - MYSQL_PASSWORD=myPassWord
      - MYSQL_ROOT_PASSWORD=myPassWord
      - MYSQL_DATABASE=my_db
    volumes:
      - mysql_vol:/var/lib/mysql
      - ./_db_restore:/docker-entrypoint-initdb.d

#volumes(root label)
volumes:
  mysql_vol: {}
