version: '3.4'
services:
  client:
    container_name: client_dev
    build:
      context: ./client
      dockerfile: Dockerfile.Dev
    restart: always
    depends_on:
      - server
    volumes:
      - ./client/src:/app/src
    environment:
      - VITE_APP_API=http://localhost:2727
      - VITE_APP_NAME=ClientFromDC
    ports:
      - 3000:3000

  server:
    container_name: server_dev
    build:
      context: ./server
      dockerfile: Dockerfile.Dev
    restart: always
    depends_on:
      - db
    volumes:
      - ./server/src:/app/src
    environment:
      - PORT=2727
      - DB_HOST=db
      - DB_USER=milon27
      - DB_PASS=myPassWord
      - DB_NAME=my_db
      - NODE_ENV=development
    ports:
      - 2727:2727

  db:
    container_name: mariadb
    image: mariadb:10.7
    restart: always
    environment:
      - MYSQL_USER=milon27
      - MYSQL_PASSWORD=myPassWord
      - MYSQL_ROOT_PASSWORD=myPassWord
      - MYSQL_DATABASE=my_db
    volumes:
      - mysql_vol:/var/lib/mysql

#volumes(root label)
volumes:
  mysql_vol: {}
