# for the production only
version: '3.4'
services:
  nginx_client:
    container_name: nginx_client
    depends_on:
      - api
    build:
      context: ./client
      target: production
    restart: always
    ports:
      - 3000:80 #client
      - 2727:2727 #api
    volumes:
      - ./_nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  api:
    container_name: server
    depends_on:
      - db
    build:
      context: ./server
      target: production
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=2727
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=myPassWord
      - DB_NAME=test_db
    # ports:
    #   - 2727:2727

  db:
    container_name: mariadb
    image: mariadb:10.7
    restart: always
    environment:
      - MYSQL_USER=milon27
      - MYSQL_PASSWORD=myPassWord
      - MYSQL_ROOT_PASSWORD=myPassWord
      - MYSQL_DATABASE=test_db
    volumes:
      - mysql_vol:/var/lib/mysql

#volumes(root label)
volumes:
  mysql_vol: {}
