version: '3.4'
services:
  client:
    container_name: client
    depends_on:
      - api
    build:
      context: ./client
      target: build
    volumes:
      - ./client/src:/app/src
    ports:
      - 3000:3000
    env_file:
      - ./client/.env
    # environment:
    #   - VITE_APP_API=http://localhost:2727/
    command: npm run dev

  api:
    container_name: server
    depends_on:
      - db
    build:
      context: ./server
      target: build
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=2727
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=myPassWord
      - DB_NAME=test_db
    volumes:
      - ./server/:/app
      - /app/node_modules
      - /app/dist
    ports:
      - 2727:2727
    command: npm run dev

  db:
    container_name: mariadb
    image: mariadb:10.7
    restart: always
    environment:
      - MYSQL_USER=milon27
      - MYSQL_PASSWORD=myPassWord
      - MYSQL_ROOT_PASSWORD=myPassWord
      - MYSQL_DATABASE=test_db
    volumes:
      - mysql_vol:/var/lib/mysql

#volumes(root label)
volumes:
  mysql_vol: {}
