version: '3.4'
services:
  nginx:
    container_name: nginx_server
    image: nginx:stable-alpine
    restart: always
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
