version: '3.4'

services:
  api:
    build:
      context: .
      target: build
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist
    ports:
      - 2727:2727
    command: npm run dev
