name: Docker CI

on:
  push:
    branches: [ clean ]
  pull_request:
    branches: [ clean ]

jobs:
  build:

    runs-on: [self-hosted, prod]
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
      name: pull the iamges & run
    - run: docker compose pull
    - run: docker compose up -d
